print("Student Management Information System")
print("Enter the following details of student")
name = input("Student Name:")
rollno = int(input("Roll No:"))
clas = input("Class:")
sec = input("Section:")
address1 = input("Address1:")
address2 = input("Address2:")
city = input("City:")
pin = int(input("Pin Code:"))
parentscontact = int(input("Parents/Guardian's Contact No:"))
print("Details you entered ")
print("Student Name :",name,"\t\t Roll No.:",rollno)
print("Class:",clas,"\t\t\t Section:",sec)
print("Address1:",address1)
print("address2:",address2)
print("City:",city,"\t\t Pin Code:",pin)
print("parents/Guardian's Contact No:",parentscontact)
